"use client";
import { store } from "@/store";
import { Toaster } from "react-hot-toast";
import { Provider } from "react-redux";
import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster />
        <Provider store={store}>
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
